apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  labels:
    app: oauth2-proxy

spec:
  replicas: 1

  selector:
    matchLabels:
      app: oauth2-proxy

  template:
    metadata:
      labels:
        app: oauth2-proxy

    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 4180

          args:
            - --provider=oidc
            - --client-id=$(OAUTH2_PROXY_CLIENT_ID)
            - --client-secret=$(OAUTH2_PROXY_CLIENT_SECRET)
            - --cookie-secret=$(OAUTH2_PROXY_COOKIE_SECRET)
            - --cookie-secure=false
            - --email-domain=*
            - --upstream=http://localhost:8080/
            - --http-address=

---
apiVersion: v1
kind: Service

metadata:
  name: oauth2-proxy-service

spec:
  selector:
    app: oauth2-proxy

  ports:
    - name: http
      port: 4180
      targetPort: 4180
      protocol: TCP
