version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: financiamento-veiculos-laravel-app
    restart: always
    tty: true
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel-network
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16-alpine
    container_name: laravel-postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE:-laravel}
      POSTGRES_USER: ${DB_USERNAME:-sail}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel-network

  redis:
    image: redis:alpine
    container_name: laravel-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - laravel-network

  prometheus:
    image: prom/prometheus:latest
    container_name: laravel-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - laravel-network

  grafana:
    image: grafana/grafana:latest
    container_name: laravel-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - laravel-network
    depends_on:
      - prometheus

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: laravel-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - laravel-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: laravel-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - laravel-network

  queue-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-queue-worker
    command: php artisan queue:work --tries=3 --timeout=90
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - app
      - postgres
      - redis
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  pgdata:
  grafana-storage:
    driver: local
